version: '2.4'

services:
  fe:
    env_file: ".env"
    build: 
      context: "./FE"
      dockerfile: Dockerfile
      #target: ${NODE_ENV}
      args:
        - "NODE_ENV=${NODE_ENV}"
    ports:
      - "${DOCKER_FE_PORT_FORWARD}:${FE_PORT}"
    volumes:
      - "./FE:/opt/FE:delegated"
      - "/opt/FE/node_modules"
    healthcheck:
      disable: true

  be:
    env_file: ".env"
    build:
      context: "./BE"
      #target: ${NODE_ENV}
      dockerfile: Dockerfile
      args:
        - "NODE_ENV=${NODE_ENV}"
    ports:
      - "${DOCKER_BE_PORT_FORWARD}:${BE_PORT}"
    volumes:
      - "./BE:/opt/BE:delegated"
      - "/opt/BE/node_modules"
    healthcheck:
      disable: true


volumes:
  notused: