FROM node:14-alpine

# set our node environment, either development or production
# defaults to production, compose overrides this to development on build and run
ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

# default to port 19006 for node, and 19001 and 19002 (tests) for debug
ENV PORT $PORT

# install global packages
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH /home/node/.npm-global/bin:$PATH
RUN npm i -g npm@latest expo-cli@latest

# install dependencies first, in a different location for easier app bind mounting for local development
# due to default /opt permissions we have to create the dir with root and change perms
#RUN mkdir /opt/FE && chown node:node /opt/FE

RUN mkdir /opt/BE
WORKDIR /opt/BE
ENV PATH /opt/FE/.bin:$PATH
COPY ./package.json package-lock.json ./
RUN npm install --force


# copy in our source code last, as it changes the most
COPY . .
# for development, we bind mount volumes; comment out for production
EXPOSE $PORTS
CMD ["npm", "start"]